 version=0.1
 [default.global.parameters]
 stack_name = "common-stack"
 
 [default.deploy.parameters]
 s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gyzp7t7gbpr7"
 s3_prefix = "common-stack"
 region = "ap-northeast-2"
 confirm_changeset = true
 capabilities = "CAPABILITY_IAM"
 tags = "project=\"my-application\" stage=\"production\""
 disable_rollback = true
 image_repositories = []